name: Container Promotion

on:
  push:
    tags:
      - test
      - prod

env:
  PROJECT: approval_sample

jobs:
  build:
    name: Container Promotion - OCP
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag, Set OpenShift Namespace Suffix
        run: echo "OS_NAMESPACE_SUFFIX=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Promote
        run: |
          echo $GITHUB_WORKSPACE
          echo "Promoting Latest Master Image to Target Environment"
          
