name: Deploy To Production
on:
  workflow_dispatch:

env:
  PROJECT: approval_sample

jobs:

  releaseNotes: 
    name: Release Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: release number + notes + commit sha 

      - name: create release


  build:
    name: Container Promotion - OCP
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag, Set OpenShift Namespace Suffix
        run: echo "OS_NAMESPACE_SUFFIX=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Promote
        run: |
          echo $GITHUB_WORKSPACE
          echo "Promoting Latest Master Image to Target Environment"
          
